
// This file has been generated by the GUI designer. Do not modify.
namespace LapseStudioGtkUI
{
	public partial class Graph
	{
		private global::Gtk.EventBox GraphEventBox;
		
		private global::Gtk.DrawingArea GraphView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LapseStudioGtkUI.Graph
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LapseStudioGtkUI.Graph";
			// Container child LapseStudioGtkUI.Graph.Gtk.Container+ContainerChild
			this.GraphEventBox = new global::Gtk.EventBox ();
			this.GraphEventBox.Name = "GraphEventBox";
			// Container child GraphEventBox.Gtk.Container+ContainerChild
			this.GraphView = new global::Gtk.DrawingArea ();
			this.GraphView.Name = "GraphView";
			this.GraphEventBox.Add (this.GraphView);
			this.Add (this.GraphEventBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.GraphEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnGraphEventBoxButtonPressEvent);
			this.GraphEventBox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnGraphEventBoxButtonReleaseEvent);
			this.GraphEventBox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnGraphEventBoxMotionNotifyEvent);
			this.GraphEventBox.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnGraphEventBoxSizeAllocated);
			this.GraphEventBox.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnGraphEventBoxExposeEvent);
		}
	}
}
