
// This file has been generated by the GUI designer. Do not modify.
namespace LapseStudioGtkUI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action MenuAction;
		private global::Gtk.Action newAction;
		private global::Gtk.Action openAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action saveAsAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action SettingsAction;
		private global::Gtk.Action preferencesAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action helpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.Action AddAction;
		private global::Gtk.Action CalculateAction;
		private global::Gtk.Action ReloadAction;
		private global::Gtk.Action ProcessAction;
		private global::Gtk.Action CancelAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar MainMenuBar;
		private global::Gtk.Toolbar MainToolBar;
		private global::Gtk.Notebook MainNotebook;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView FileTree;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Image ThumbViewList;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Label TabPageLabel1;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label TabPageLabel2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Button YToStartButton;
		private global::Gtk.Button AlignXButton;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Button YToEndButton;
		private global::Gtk.Button ResetGraphButton;
		private global::Gtk.Image ThumbViewGraph;
		private global::Gtk.HScale FrameSelectScale;
		private global::Gtk.Button ThumbEditButton;
		private global::Gtk.Image ThumbEditView;
		private global::Gtk.HScale BrightnessScale;
		private global::Gtk.Fixed fixed4;
		private global::LapseStudioGtkUI.Graph MainGraph;
		private global::Gtk.Label TabPageLabel3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ProgressBar MainProgressBar;
		private global::Gtk.Label StatusLabel;
		private global::Gtk.Fixed fixed1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LapseStudioGtkUI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.MenuAction = new global::Gtk.Action ("MenuAction", global::Mono.Unix.Catalog.GetString ("Menu"), null, null);
			this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Menu");
			w1.Add (this.MenuAction, null);
			this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New Project"), null, "gtk-new");
			this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Project");
			w1.Add (this.newAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open Project"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Project");
			w1.Add (this.openAction, null);
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save Project"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Project");
			w1.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save Project As"), null, "gtk-save-as");
			this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Project As");
			w1.Add (this.saveAsAction, null);
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.quitAction, null);
			this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.SettingsAction, null);
			this.preferencesAction = new global::Gtk.Action ("preferencesAction", global::Mono.Unix.Catalog.GetString ("General Settings"), null, "gtk-preferences");
			this.preferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("General Settings");
			w1.Add (this.preferencesAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
			this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.helpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.AddAction = new global::Gtk.Action ("AddAction", null, global::Mono.Unix.Catalog.GetString ("Add Frames"), "AddIcon32x32");
			w1.Add (this.AddAction, null);
			this.CalculateAction = new global::Gtk.Action ("CalculateAction", null, global::Mono.Unix.Catalog.GetString ("Calculate Brightnes"), "CalculateIcon32x32");
			w1.Add (this.CalculateAction, null);
			this.ReloadAction = new global::Gtk.Action ("ReloadAction", null, global::Mono.Unix.Catalog.GetString ("Reload XMP"), "ReloadIcon32x32");
			w1.Add (this.ReloadAction, null);
			this.ProcessAction = new global::Gtk.Action ("ProcessAction", null, global::Mono.Unix.Catalog.GetString ("Process Frames"), "SaveIcon32x32");
			w1.Add (this.ProcessAction, null);
			this.CancelAction = new global::Gtk.Action ("CancelAction", null, global::Mono.Unix.Catalog.GetString ("Cancel"), "CancelIcon32x32");
			w1.Add (this.CancelAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "LapseStudioGtkUI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("LapseStudio");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child LapseStudioGtkUI.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='MainMenuBar'><menu name='MenuAction' action='MenuAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='preferencesAction' action='preferencesAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='helpAction' action='helpAction'/><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.MainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenuBar")));
			this.MainMenuBar.Name = "MainMenuBar";
			this.vbox1.Add (this.MainMenuBar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MainMenuBar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='MainToolBar'><toolitem name='AddAction' action='AddAction'/><toolitem name='CalculateAction' action='CalculateAction'/><toolitem name='ReloadAction' action='ReloadAction'/><toolitem name='ProcessAction' action='ProcessAction'/><toolitem name='CancelAction' action='CancelAction'/></toolbar></ui>");
			this.MainToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/MainToolBar")));
			this.MainToolBar.Name = "MainToolBar";
			this.MainToolBar.ShowArrow = false;
			this.MainToolBar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.MainToolBar.IconSize = ((global::Gtk.IconSize)(3));
			this.vbox1.Add (this.MainToolBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MainToolBar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.MainNotebook = new global::Gtk.Notebook ();
			this.MainNotebook.CanFocus = true;
			this.MainNotebook.Name = "MainNotebook";
			this.MainNotebook.CurrentPage = 0;
			// Container child MainNotebook.Gtk.Notebook+NotebookChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.FileTree = new global::Gtk.TreeView ();
			this.FileTree.CanFocus = true;
			this.FileTree.Name = "FileTree";
			this.GtkScrolledWindow.Add (this.FileTree);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
			w5.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.ThumbViewList = new global::Gtk.Image ();
			this.ThumbViewList.WidthRequest = 160;
			this.ThumbViewList.HeightRequest = 120;
			this.ThumbViewList.Name = "ThumbViewList";
			this.vbox2.Add (this.ThumbViewList);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.ThumbViewList]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox2.Add (this.fixed2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed2]));
			w7.Position = 1;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.MainNotebook.Add (this.hbox2);
			// Notebook tab
			this.TabPageLabel1 = new global::Gtk.Label ();
			this.TabPageLabel1.Name = "TabPageLabel1";
			this.TabPageLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Files");
			this.MainNotebook.SetTabLabel (this.hbox2, this.TabPageLabel1);
			this.TabPageLabel1.ShowAll ();
			// Container child MainNotebook.Gtk.Notebook+NotebookChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.MainNotebook.Add (this.fixed3);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook [this.fixed3]));
			w10.Position = 1;
			// Notebook tab
			this.TabPageLabel2 = new global::Gtk.Label ();
			this.TabPageLabel2.Name = "TabPageLabel2";
			this.TabPageLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("Calculation");
			this.MainNotebook.SetTabLabel (this.fixed3, this.TabPageLabel2);
			this.TabPageLabel2.ShowAll ();
			// Container child MainNotebook.Gtk.Notebook+NotebookChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.YToStartButton = new global::Gtk.Button ();
			this.YToStartButton.WidthRequest = 75;
			this.YToStartButton.CanFocus = true;
			this.YToStartButton.Name = "YToStartButton";
			this.YToStartButton.UseUnderline = true;
			this.YToStartButton.Label = global::Mono.Unix.Catalog.GetString ("Y To Start");
			this.vbox4.Add (this.YToStartButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.YToStartButton]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.AlignXButton = new global::Gtk.Button ();
			this.AlignXButton.WidthRequest = 75;
			this.AlignXButton.CanFocus = true;
			this.AlignXButton.Name = "AlignXButton";
			this.AlignXButton.UseUnderline = true;
			this.AlignXButton.Label = global::Mono.Unix.Catalog.GetString ("Align X");
			this.vbox4.Add (this.AlignXButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.AlignXButton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox4.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(2));
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.YToEndButton = new global::Gtk.Button ();
			this.YToEndButton.WidthRequest = 75;
			this.YToEndButton.CanFocus = true;
			this.YToEndButton.Name = "YToEndButton";
			this.YToEndButton.UseUnderline = true;
			this.YToEndButton.Label = global::Mono.Unix.Catalog.GetString ("Y To End");
			this.vbox5.Add (this.YToEndButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.YToEndButton]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ResetGraphButton = new global::Gtk.Button ();
			this.ResetGraphButton.WidthRequest = 75;
			this.ResetGraphButton.CanFocus = true;
			this.ResetGraphButton.Name = "ResetGraphButton";
			this.ResetGraphButton.UseUnderline = true;
			this.ResetGraphButton.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.vbox5.Add (this.ResetGraphButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.ResetGraphButton]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.hbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.ThumbViewGraph = new global::Gtk.Image ();
			this.ThumbViewGraph.WidthRequest = 160;
			this.ThumbViewGraph.HeightRequest = 120;
			this.ThumbViewGraph.Name = "ThumbViewGraph";
			this.vbox3.Add (this.ThumbViewGraph);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ThumbViewGraph]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.FrameSelectScale = new global::Gtk.HScale (null);
			this.FrameSelectScale.CanFocus = true;
			this.FrameSelectScale.Name = "FrameSelectScale";
			this.FrameSelectScale.Adjustment.Upper = 100D;
			this.FrameSelectScale.Adjustment.PageIncrement = 10D;
			this.FrameSelectScale.Adjustment.StepIncrement = 1D;
			this.FrameSelectScale.DrawValue = true;
			this.FrameSelectScale.Digits = 0;
			this.FrameSelectScale.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox3.Add (this.FrameSelectScale);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.FrameSelectScale]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ThumbEditButton = new global::Gtk.Button ();
			this.ThumbEditButton.CanFocus = true;
			this.ThumbEditButton.Name = "ThumbEditButton";
			this.ThumbEditButton.UseUnderline = true;
			this.ThumbEditButton.Label = global::Mono.Unix.Catalog.GetString ("Edit Thumbs");
			this.vbox3.Add (this.ThumbEditButton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ThumbEditButton]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.ThumbEditView = new global::Gtk.Image ();
			this.ThumbEditView.WidthRequest = 160;
			this.ThumbEditView.HeightRequest = 120;
			this.ThumbEditView.Name = "ThumbEditView";
			this.vbox3.Add (this.ThumbEditView);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.ThumbEditView]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.BrightnessScale = new global::Gtk.HScale (null);
			this.BrightnessScale.CanFocus = true;
			this.BrightnessScale.Name = "BrightnessScale";
			this.BrightnessScale.Adjustment.Lower = -100D;
			this.BrightnessScale.Adjustment.Upper = 100D;
			this.BrightnessScale.Adjustment.PageIncrement = 10D;
			this.BrightnessScale.Adjustment.StepIncrement = 1D;
			this.BrightnessScale.DrawValue = true;
			this.BrightnessScale.Digits = 0;
			this.BrightnessScale.ValuePos = ((global::Gtk.PositionType)(3));
			this.vbox3.Add (this.BrightnessScale);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.BrightnessScale]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.vbox3.Add (this.fixed4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed4]));
			w23.Position = 6;
			this.hbox3.Add (this.vbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.MainGraph = new global::LapseStudioGtkUI.Graph ();
			this.MainGraph.Events = ((global::Gdk.EventMask)(256));
			this.MainGraph.Name = "MainGraph";
			this.hbox3.Add (this.MainGraph);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.MainGraph]));
			w25.Position = 1;
			this.MainNotebook.Add (this.hbox3);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook [this.hbox3]));
			w26.Position = 2;
			// Notebook tab
			this.TabPageLabel3 = new global::Gtk.Label ();
			this.TabPageLabel3.Name = "TabPageLabel3";
			this.TabPageLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Graph");
			this.MainNotebook.SetTabLabel (this.hbox3, this.TabPageLabel3);
			this.TabPageLabel3.ShowAll ();
			this.vbox1.Add (this.MainNotebook);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.MainNotebook]));
			w27.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.MainProgressBar = new global::Gtk.ProgressBar ();
			this.MainProgressBar.WidthRequest = 160;
			this.MainProgressBar.Name = "MainProgressBar";
			this.hbox1.Add (this.MainProgressBar);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.MainProgressBar]));
			w28.Position = 0;
			w28.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.StatusLabel = new global::Gtk.Label ();
			this.StatusLabel.Name = "StatusLabel";
			this.StatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Everything ok");
			this.hbox1.Add (this.StatusLabel);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.StatusLabel]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			w29.Padding = ((uint)(20));
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
			w30.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 816;
			this.DefaultHeight = 662;
			this.Show ();
			this.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnExposeEvent);
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferencesActionActivated);
			this.helpAction.Activated += new global::System.EventHandler (this.OnHelpActionActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.AddAction.Activated += new global::System.EventHandler (this.OnAddActionActivated);
			this.CalculateAction.Activated += new global::System.EventHandler (this.OnCalculateActionActivated);
			this.ReloadAction.Activated += new global::System.EventHandler (this.OnReloadActionActivated);
			this.ProcessAction.Activated += new global::System.EventHandler (this.OnProcessActionActivated);
			this.CancelAction.Activated += new global::System.EventHandler (this.OnCancelActionActivated);
			this.YToStartButton.Clicked += new global::System.EventHandler (this.OnYToStartButtonClicked);
			this.AlignXButton.Clicked += new global::System.EventHandler (this.OnAlignXButtonClicked);
			this.YToEndButton.Clicked += new global::System.EventHandler (this.OnYToEndButtonClicked);
			this.ResetGraphButton.Clicked += new global::System.EventHandler (this.OnResetGraphButtonClicked);
			this.FrameSelectScale.ValueChanged += new global::System.EventHandler (this.OnFrameSelectScaleValueChanged);
			this.BrightnessScale.ValueChanged += new global::System.EventHandler (this.OnBrightnessScaleValueChanged);
		}
	}
}
