
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry PP3PathBox1;
	private global::Gtk.Entry PP3PathBox2;
	private global::Gtk.Button BrowseButton1;
	private global::Gtk.Button BrowseButton2;
	private global::Gtk.Button CompareVersionsButton;
	private global::Gtk.Button SingleVersionButton;
	private global::Gtk.Button BatchComparisonButton;
	private global::Gtk.Button SaveCodeButton;
	private global::Gtk.Button SavePP3DefinitionButton;
	private global::Gtk.Button CompareSameButton;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView TreeView1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView TreeView2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "PP3 Toolbox";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.HeightRequest = 120;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PP3PathBox1 = new global::Gtk.Entry ();
		this.PP3PathBox1.WidthRequest = 360;
		this.PP3PathBox1.CanFocus = true;
		this.PP3PathBox1.Name = "PP3PathBox1";
		this.PP3PathBox1.IsEditable = false;
		this.PP3PathBox1.InvisibleChar = '●';
		this.fixed1.Add (this.PP3PathBox1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PP3PathBox1]));
		w1.X = 15;
		w1.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.PP3PathBox2 = new global::Gtk.Entry ();
		this.PP3PathBox2.WidthRequest = 360;
		this.PP3PathBox2.CanFocus = true;
		this.PP3PathBox2.Name = "PP3PathBox2";
		this.PP3PathBox2.IsEditable = false;
		this.PP3PathBox2.InvisibleChar = '●';
		this.fixed1.Add (this.PP3PathBox2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.PP3PathBox2]));
		w2.X = 15;
		w2.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BrowseButton1 = new global::Gtk.Button ();
		this.BrowseButton1.CanFocus = true;
		this.BrowseButton1.Name = "BrowseButton1";
		this.BrowseButton1.UseUnderline = true;
		this.BrowseButton1.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.fixed1.Add (this.BrowseButton1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BrowseButton1]));
		w3.X = 385;
		w3.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BrowseButton2 = new global::Gtk.Button ();
		this.BrowseButton2.CanFocus = true;
		this.BrowseButton2.Name = "BrowseButton2";
		this.BrowseButton2.UseUnderline = true;
		this.BrowseButton2.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.fixed1.Add (this.BrowseButton2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BrowseButton2]));
		w4.X = 385;
		w4.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CompareVersionsButton = new global::Gtk.Button ();
		this.CompareVersionsButton.WidthRequest = 115;
		this.CompareVersionsButton.CanFocus = true;
		this.CompareVersionsButton.Name = "CompareVersionsButton";
		this.CompareVersionsButton.UseUnderline = true;
		this.CompareVersionsButton.Label = global::Mono.Unix.Catalog.GetString ("Compare Versions");
		this.fixed1.Add (this.CompareVersionsButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CompareVersionsButton]));
		w5.X = 450;
		w5.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SingleVersionButton = new global::Gtk.Button ();
		this.SingleVersionButton.WidthRequest = 115;
		this.SingleVersionButton.CanFocus = true;
		this.SingleVersionButton.Name = "SingleVersionButton";
		this.SingleVersionButton.UseUnderline = true;
		this.SingleVersionButton.Label = global::Mono.Unix.Catalog.GetString ("Single Version");
		this.fixed1.Add (this.SingleVersionButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SingleVersionButton]));
		w6.X = 450;
		w6.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BatchComparisonButton = new global::Gtk.Button ();
		this.BatchComparisonButton.WidthRequest = 115;
		this.BatchComparisonButton.CanFocus = true;
		this.BatchComparisonButton.Name = "BatchComparisonButton";
		this.BatchComparisonButton.UseUnderline = true;
		this.BatchComparisonButton.Label = global::Mono.Unix.Catalog.GetString ("Batch Comparison");
		this.fixed1.Add (this.BatchComparisonButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BatchComparisonButton]));
		w7.X = 580;
		w7.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SaveCodeButton = new global::Gtk.Button ();
		this.SaveCodeButton.CanFocus = true;
		this.SaveCodeButton.Name = "SaveCodeButton";
		this.SaveCodeButton.UseUnderline = true;
		this.SaveCodeButton.Label = global::Mono.Unix.Catalog.GetString ("Save Code");
		this.fixed1.Add (this.SaveCodeButton);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SaveCodeButton]));
		w8.X = 15;
		w8.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.SavePP3DefinitionButton = new global::Gtk.Button ();
		this.SavePP3DefinitionButton.CanFocus = true;
		this.SavePP3DefinitionButton.Name = "SavePP3DefinitionButton";
		this.SavePP3DefinitionButton.UseUnderline = true;
		this.SavePP3DefinitionButton.Label = global::Mono.Unix.Catalog.GetString ("Save PP3 Definition");
		this.fixed1.Add (this.SavePP3DefinitionButton);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SavePP3DefinitionButton]));
		w9.X = 100;
		w9.Y = 85;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CompareSameButton = new global::Gtk.Button ();
		this.CompareSameButton.WidthRequest = 115;
		this.CompareSameButton.CanFocus = true;
		this.CompareSameButton.Name = "CompareSameButton";
		this.CompareSameButton.UseUnderline = true;
		this.CompareSameButton.Label = global::Mono.Unix.Catalog.GetString ("Compare Same");
		this.fixed1.Add (this.CompareSameButton);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CompareSameButton]));
		w10.X = 580;
		w10.Y = 45;
		this.vbox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 366;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TreeView1 = new global::Gtk.TreeView ();
		this.TreeView1.CanFocus = true;
		this.TreeView1.Name = "TreeView1";
		this.TreeView1.EnableSearch = false;
		this.GtkScrolledWindow.Add (this.TreeView1);
		this.hpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w13 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
		w13.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.TreeView2 = new global::Gtk.TreeView ();
		this.TreeView2.CanFocus = true;
		this.TreeView2.Name = "TreeView2";
		this.TreeView2.EnableSearch = false;
		this.GtkScrolledWindow1.Add (this.TreeView2);
		this.hpaned1.Add (this.GtkScrolledWindow1);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w16.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 739;
		this.DefaultHeight = 630;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BrowseButton1.Clicked += new global::System.EventHandler (this.OnBrowseButton1Clicked);
		this.BrowseButton2.Clicked += new global::System.EventHandler (this.OnBrowseButton2Clicked);
		this.CompareVersionsButton.Clicked += new global::System.EventHandler (this.OnCompareVersionsButtonClicked);
		this.SingleVersionButton.Clicked += new global::System.EventHandler (this.OnSingleVersionButtonClicked);
		this.BatchComparisonButton.Clicked += new global::System.EventHandler (this.OnBatchComparisonButtonClicked);
		this.SaveCodeButton.Clicked += new global::System.EventHandler (this.OnSaveCodeButtonClicked);
		this.SavePP3DefinitionButton.Clicked += new global::System.EventHandler (this.OnSavePP3DefinitionButtonClicked);
		this.CompareSameButton.Clicked += new global::System.EventHandler (this.OnCompareSameButtonClicked);
	}
}
