// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace LapseStudioMacUI
{
	public partial class SettingsDialog : NSWindow
	{
		public SettingsDialog (IntPtr handle) : base (handle)
		{
		}
	}
}
